baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Hofstadter Studios Documentation"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
editURL = "https://github.com/hofstadter-io/studios-docs/edit/master/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fa fa-code'></i> <label>__TAG__</label>"
url = "/versions"
weight = 5

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github</label>"
identifier = "ds"
url = "https://github.com/hofstadter-io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-flask'></i> <label>Studios</label>"
url = "https://studios.hofstadter.io"
weight = 30
