apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5

  template:

    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      nodeSelector:
        hof: studios

      tolerations:
      - effect: NoSchedule
        key: hof
        operator: Equal
        value: studios
      - key: "sandbox.gke.io/runtime"
        operator: "Equal"
        value: "gvisor"
        effect: "NoSchedule"

      containers:
      - name: website
        image: "us.gcr.io/{{ .Values.project }}/docs.hofstadter.io:{{ .Values.version }}"
        ports:
        - containerPort: 80
          protocol: "TCP"

        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          failureThreshold: 3
          periodSeconds: 60


