apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  tls:
  - hosts:
    - {{ .Values.domain | quote }}
    secretName: {{ .Release.Name }}-tls

  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
        - backend:
            serviceName: {{ .Release.Name }}
            servicePort: 80

