apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}

  # only allow traffic in the same namespace, on specified port
  policyTypes:
  - Ingress
  ingress:
  - from:
    # For Nginx-ingress
    - namespaceSelector:     # chooses all pods in namespaces labelled with team=operations
        matchLabels:
          role: ingress
      podSelector:           # chooses pods with type=monitoring
        matchLabels:
          app: nginx-ingress
    ports:
    - protocol: TCP
      port: 80

