steps:

- name: 'gcr.io/cloud-builders/git'
  args: [ 'submodule', 'update',  '--init' ]

- name: 'gcr.io/hof-io--system/hugo:0.53'
  args: ['--baseURL', 'https://docs.hofstadter.io', '-d', 'dist']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/docs.hofstadter.io:$BRANCH_NAME', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us.gcr.io/$PROJECT_ID/docs.hofstadter.io:$BRANCH_NAME' ]

