apiVersion: apps/v1
kind: Deployment
metadata:
  name: hof-docs
  namespace: websites
  labels:
    app: hof-docs
spec:
  selector:
    matchLabels:
      app: hof-docs

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5

  template:
    metadata:
      labels:
        app: hof-docs
        version: "__SHA__"
    spec:
      containers:
      - name: website
        image: gcr.io/hof-io--system/docs.hofstadter.io:__BRANCH__
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: "TCP"

        readinessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 6
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 6
          failureThreshold: 3
          periodSeconds: 10


