apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hof-documentation-website
  namespace: websites
  labels:
    app: hof-documentation-website
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"

spec:
  tls:
  - hosts:
    - docs.hofstadter.io
    secretName: docs-hofstadter-io-tls

  rules:
  - host: docs.hofstadter.io
    http:
      paths:
        - backend:
            serviceName: hof-documentation-website
            servicePort: 80

